# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Authorization: Token 30c528a5e7eb94951be328b650395f5f751aabed
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 30c528a5e7eb94951be328b650395f5f751aabed

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 30c528a5e7eb94951be328b650395f5f751aabed

{
  "status": "DRAFT"
}

###

DELETE {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 30c528a5e7eb94951be328b650395f5f751aabed

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Authorization: Token 30c528a5e7eb94951be328b650395f5f751aabed
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-05-12
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=DRAFT
Content-Type: application/json
